# Autogenerated wrapper script for s5cmd_jll for armv7l-linux-gnueabihf
export s5cmd

JLLWrappers.@generate_wrapper_header("s5cmd")
JLLWrappers.@declare_executable_product(s5cmd)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        s5cmd,
        "bin/s5cmd",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
